"""add notificaciones

Revision ID: e8ae79159c75
Revises: 
Create Date: 2026-03-02 15:22:37.981056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8ae79159c75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administradores')
    op.alter_column('registro_acceso', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('registro_acceso', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_unique_constraint(None, 'usuarios', ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('registro_acceso', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('registro_acceso', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('administradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('administradores_pkey')),
    sa.UniqueConstraint('username', name=op.f('administradores_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
